// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLaoCb7CIAeEj39HfMIrKPP5rP73yD0U',
    appId: '1:378675941206:web:3042d475f84383ad9cd0f7',
    messagingSenderId: '378675941206',
    projectId: 'eventapp-bd9cb',
    authDomain: 'eventapp-bd9cb.firebaseapp.com',
    storageBucket: 'eventapp-bd9cb.firebasestorage.app',
    measurementId: 'G-5LJXMX7YSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrcMvKSUbuWP_VzTEbFgx8Z_BIZPnzY4',
    appId: '1:378675941206:android:9e77e77ceb2ac0449cd0f7',
    messagingSenderId: '378675941206',
    projectId: 'eventapp-bd9cb',
    storageBucket: 'eventapp-bd9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU6dv-Q5FvRXPiS4hEH0UTfcexydlK_E',
    appId: '1:378675941206:ios:70f020ae54cb66f49cd0f7',
    messagingSenderId: '378675941206',
    projectId: 'eventapp-bd9cb',
    storageBucket: 'eventapp-bd9cb.firebasestorage.app',
    iosBundleId: 'com.example.eventsbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANU6dv-Q5FvRXPiS4hEH0UTfcexydlK_E',
    appId: '1:378675941206:ios:70f020ae54cb66f49cd0f7',
    messagingSenderId: '378675941206',
    projectId: 'eventapp-bd9cb',
    storageBucket: 'eventapp-bd9cb.firebasestorage.app',
    iosBundleId: 'com.example.eventsbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLaoCb7CIAeEj39HfMIrKPP5rP73yD0U',
    appId: '1:378675941206:web:48b9e98c652d196b9cd0f7',
    messagingSenderId: '378675941206',
    projectId: 'eventapp-bd9cb',
    authDomain: 'eventapp-bd9cb.firebaseapp.com',
    storageBucket: 'eventapp-bd9cb.firebasestorage.app',
    measurementId: 'G-YSQ2F3JQ4B',
  );
}
